#' Perform LOO cross-validation IMPROPERLY; in particular, perform
#' preprocessing step BEFORE data splitting according to the main
#' example of Moscovich and Rosset (2022). The covariates with the K
#' largest empirical variance are selected for prediction prior to 
#' data splitting.
#' 
#' Input:
#' data_list - Results of simulation as generated by generate_sample
#' p - Number of predictors before preprocessing performed
#' K - Number of predictors to be selected according to largest variance
#' sample_size - number of simulated data points
#' 
#' Output:
#' MSE_Mean_Incorrect - Average of all MSEs across folds 

source('src/feature_select_var.R')

improper_cv_LOO <- function(data_list, p, K = 10, sample_size) {
  
  output_values <- data_list$y
  covariates <- data_list$X
  
  # Preprocessing on entire dataset
  selected_variables <- feature_select_var(covariates, K)
  
  mse_full <- numeric(length = sample_size)
  
  for (i in 1:sample_size) {
    
    # Split into training/testing covariates
    training_data <- as.data.frame(matrix(
      selected_variables$X_K_highest_var[c(1:sample_size)[-i], ], ncol = K))
    testing_data <- as.data.frame(matrix(
      selected_variables$X_K_highest_var[i, ], ncol = K))
    
    # Split into training/testing outputs
    output_values_train <- output_values[-i]
    output_values_test <- output_values[i]
    
    all_data_training <- cbind(training_data, output_values_train)
    all_data_testing <- cbind(testing_data, output_values_test)
    
    # Producing Model on training data
    my_model <- lm(output_values_train ~ . + 0, 
                  data = all_data_training)
    
    # Predicting on test subset
    my_predictions <- predict(my_model, 
                              newdata = all_data_testing)
    
    # Computing MSE for this Fold
    mse_full[i] <- mean((all_data_testing$output_values_test - my_predictions)^2)
    
  }
  
  # Mean MSE Across Folds
  MSE_Mean_Incorrect <- mean(mse_full)
  
  return(MSE_Mean_Incorrect)
}