#' Perform cross-validation improperly; in particular, perform
#' preprocessing step before data splitting according to the main
#' example of Moscovich and Rosset (2002). The covariates with the K
#' largest empirical variance are selected for prediction prior to 
#' data splitting.
#' 
#' Input:
#' data_list - Results of simulation as generated by generate_sample
#' p - Number of predictors before preprocessing performed
#' K - Number of predictors to be selected according to largest variance
#' folds - Indices for folds from leave-one-out cross validation. For the 
#'         functions that follow, these are generated using the createFolds() 
#'         function in the caret package.

improper_cv <- function(data_list, p, K = 10, folds) {
  
  outputValues <- data_list$y
  covariates <- data_list$X
  
  ### Preprocessing on entire dataset
  selected_variables <- var_select(covariates, K)
  
  ### Performing Cross Validation
  mse_full <- numeric(length = length(folds))
  
  for (i in seq_along(folds)) {
    
    training_ID <- folds[[i]]
    trainingData <- matrix(selected_variables$XhighVar[training_ID, ], ncol = K)
    testingData <- matrix(data = selected_variables$XhighVar[-training_ID, ], ncol = K)
    
    trainingData <- as.data.frame(trainingData)
    testingData <- as.data.frame(testingData)
    
    outputValues_train <- outputValues[training_ID]
    outputValues_test <- outputValues[-training_ID]
    
    finalTraining <- cbind(trainingData, outputValues_train)
    finalTesting <- cbind(testingData, outputValues_test)
    
    ### Producing Model on training data
    myModel <- lm(outputValues_train ~ . + 0, 
                  data = finalTraining)
    
    ### Predicting on test subset
    my_predictions <- predict(myModel, 
                              newdata = finalTesting)
    
    ### Computing MSE for this Fold
    mse_full[i] <- mean((finalTesting$outputValues_test - my_predictions)^2)
    
  }
  
  ### Mean MSE Across Folds
  MSE_Mean_Full <- mean(mse_full)
  
  return(MSE_Mean_Full)
}