#' Perform LOO cross-validation PROPERLY; in particular, perform
#' preprocessing step AFTER data splitting according to the main
#' example of Moscovich and Rosset (2022). The covariates with the K
#' largest empirical variance are selected for prediction prior to 
#' data splitting.
#' 
#' Input:
#' data_list - Results of simulation as generated by generate_sample
#' p - Number of predictors before preprocessing performed
#' K - Number of predictors to be selected according to largest variance
#' sample_size - number of simulated data points
#' 
#' Output:
#' MSE_Mean_Correct - Mean of MSEs after performing CV

source('src/feature_select_var.R')

proper_cv_LOO <- function(data_list, p, K = 10, sample_size) {
  
  output_values <- data_list$y
  covariates <- data_list$X
  
  # Checking dimensions agree
  if (length(output_values) != nrow(covariates)) stop("Length of y must match nrow(covariates)")
  
  # Checking sample size
  if (is.null(sample_size)) sample_size <- nrow(covariates)
  
  # Checking sample_size and nrow(covariates) agree
  if (sample_size != nrow(covariates)) stop("For LOO CV, sample_size must equal nrow(covariates)")
  
  # Checking that p is supplied and is positive whole number
  if (!is.numeric(p) || !(p > 0) || !(p %% 1 == 0)) stop("p must be a positive whole number")
  
  # Performing Cross Validation Correctly
  mse_correct <- numeric(length = sample_size)
  
  for (i in 1:sample_size) {
    
    # Splitting Data into Training/Testing Sets for this fold
    train_covariates <- covariates[c(1:sample_size)[-i], ]
    train_output <- output_values[-i]
    
    test_covariates <- matrix(data = covariates[i, ], ncol = p)
    test_output <- output_values[i]
    
    # Selecting high variance variables (only training data!)
    selected_variables <- feature_select_var(train_covariates, K)
    
    # Selecting variables only on the basis of training data
    train_covariates <- as.data.frame(matrix(
      train_covariates[, selected_variables$highest_var_ID], ncol = K))
    
    test_covariates <- as.data.frame(matrix(
      test_covariates[, selected_variables$highest_var_ID], ncol = K))
    
    # Creating final data frames
    all_data_training <- cbind(train_covariates, train_output)
    all_data_testing <- cbind(test_covariates, test_output)
    
    # Creating model
    my_model <- lm(train_output ~ . + 0, 
                  data = all_data_training)
    
    # Making predictions
    pred <- predict(my_model, 
                    newdata = all_data_testing)
    
    # Computing MSE
    mse_correct[i] <- mean((all_data_testing$test_output - pred)^2)
    
  }
  
  # Mean MSE Across Folds
  MSE_Mean_Correct <- mean(mse_correct)
  
  return(MSE_Mean_Correct)
  
}