#' Perform 2-fold cross-validation PROPERLY; in particular, perform
#' preprocessing step AFTER data splitting according to the main
#' example of Moscovich and Rosset (2022). The covariates with the K
#' largest empirical variance are selected for prediction prior to 
#' data splitting.
#' 
#' Input:
#' data_list - Results of simulation as generated by generate_sample
#' p - Number of predictors before preprocessing performed
#' K - Number of predictors to be selected according to largest variance
#' sample_size - number of simulated data points
#' seed - seed for reproducibility
#' 
#' Output:
#' MSE_Mean_Correct - Mean of MSEs after performing CV

source('src/feature_select_var.R')

proper_cv_2fold <- function(data_list, p, K = 10, sample_size, seed) {
  
  y <- data_list$y
  X <- data_list$X
  
  # Make two roughly equal folds, set seed for reproducibility
  set.seed(seed)
  idx_all <- sample.int(sample_size)
  folds <- split(idx_all, rep(1:2, length.out = sample_size))  
  
  mse_fold <- numeric(2)
  
  for (f in 1:2) {
    
    test_idx  <- folds[[f]]
    train_idx <- setdiff(seq_len(sample_size), test_idx)
    
    # Split into training/testing data
    X_train <- X[train_idx, , drop = FALSE]
    y_train <- y[train_idx]
    X_test  <- X[test_idx,  , drop = FALSE]
    y_test  <- y[test_idx]
    
    # Proper preprocessing: select features using TRAINING data only
    sel <- feature_select_var(X_train, K)              
    keep <- sel$highest_var_ID
    X_train_k <- as.data.frame(X_train[, keep, drop = FALSE])
    X_test_k  <- as.data.frame(X_test[,  keep, drop = FALSE])
    
    # Consistent column names for model matrix
    colnames(X_train_k) <- colnames(X_test_k) <- paste0("X", seq_len(ncol(X_train_k)))
    
    # Fit on training fold 
    train_df <- cbind(X_train_k, train_output = y_train)
    fit <- lm(train_output ~ . + 0, data = train_df)
    
    # Predict on held-out fold and compute fold MSE
    y_hat <- predict(fit, newdata = X_test_k)
    mse_fold[f] <- mean((y_test - y_hat)^2)
  }
  
  # Compute mean across folds
  MSE_Mean_Correct <- mean(mse_fold)
  return(MSE_Mean_Correct)
}

